/* Every visible label on the blog sub-site.

   Language and theme themselves live in src/shared/prefs — this file is only
   the strings. Two parallel objects so TypeScript rejects a label that exists
   in one language and not the other. */

export const ui = {
  en: {
    home: "Home",
    searchPlaceholder: "Search essays",
    searchLabel: "Search essays",
    clearSearch: "Clear search",
    all: "All",
    result: (n: number) => `${n} ${n === 1 ? "result" : "results"}`,
    noMatch: "No essays match that search.",
    noSection: "Nothing filed here yet.",
    columns: "Columns",
    tags: "Tags",
    topics: "Topics",
    latest: "Latest",
    topicLabel: "Topics",
    allPosts: "All essays",
    backToHub: "Back to the hub",
    backToIndex: "All essays",
    backToTop: "Back to top",
    onThisPage: (n?: number) =>
      n === undefined ? "On this page" : `On this page · ${n}`,
    previous: "Previous",
    next: "Next",
    related: "Related reading",
    taggedUnder: "Tags",
    copyCode: "Copy code",
    copied: "Copied",
    loading: "Loading",
    loadFailed: "Could not load this essay.",
    retry: "Try again",
    alsoIn: (n: number) => `${n} more in this column`,
    readTime: (m: string) => m,
    thisEssay: "This essay",
    otherLanguage: "Read in",
    empty: "No essays have been published yet.",
    noTag: "No essays under this tag yet.",
    posts: "essays",
    end: (year: number) => `End — © ${year} Eververdants`,
  },
  zh: {
    home: "首页",
    searchPlaceholder: "搜索文章",
    searchLabel: "搜索文章",
    clearSearch: "清除搜索",
    all: "全部",
    result: (n: number) => `${n} 条结果`,
    noMatch: "没有匹配的文章。",
    noSection: "这里还没有归档文章。",
    columns: "栏目",
    tags: "标签",
    topics: "专题",
    latest: "最新",
    topicLabel: "所属专题",
    allPosts: "全部文章",
    backToHub: "返回导航页",
    backToIndex: "全部文章",
    backToTop: "回到顶部",
    onThisPage: (n?: number) =>
      n === undefined ? "本页目录" : `本页目录 · ${n}`,
    previous: "上一篇",
    next: "下一篇",
    related: "延伸阅读",
    taggedUnder: "标签",
    copyCode: "复制代码",
    copied: "已复制",
    loading: "载入中",
    loadFailed: "这篇文章没能加载。",
    retry: "重试",
    alsoIn: (n: number) => `本栏目还有 ${n} 篇`,
    readTime: (m: string) => m,
    thisEssay: "本篇",
    otherLanguage: "阅读语言",
    empty: "还没有发布文章。",
    noTag: "该标签下暂无文章。",
    posts: "篇文章",
    end: (year: number) => `完 — © ${year} Eververdants`,
  },
} as const;

export type Ui = (typeof ui)["en"];
