/* Every visible label on the blog sub-site.

   Language and theme themselves live in src/shared/prefs — this file is only
   the strings. The two objects are kept parallel by hand: nothing in the
   type system enforces that today, so a label added to one language has to
   be added to the other. */

export const ui = {
  en: {
    searchPlaceholder: "Search essays",
    searchLabel: "Search essays",
    clearSearch: "Clear search",
    all: "All",
    result: (n: number) => `${n} ${n === 1 ? "result" : "results"}`,
    noMatch: "No essays match that search.",
    noSection: "Nothing filed here yet.",
    columns: "Columns",
    tags: "Tags",
    topics: "Topics",
    latest: "Latest",
    topicLabel: "Topics",
    backToHub: "Back to the hub",
    backToIndex: "All essays",
    backToTop: "Back to top",
    onThisPage: (n?: number) =>
      n === undefined ? "On this page" : `On this page · ${n}`,
    previous: "Previous",
    next: "Next",
    related: "Related reading",
    taggedUnder: "Tags",
    references: "References",
    copyCode: "Copy code",
    copied: "Copied",
    copyFailed: "Copy failed",
    share: "Share",
    copyLink: "Copy link",
    shared: "Copied",
    linkCopied: "Copied",
    openImage: "Open image viewer",
    lightbox: "Image viewer",
    loading: "Loading",
    loadFailed: "Could not load this essay.",
    retry: "Try again",
    empty: "No essays have been published yet.",
    noTag: "No essays under this tag yet.",
    posts: "essays",
    end: (year: number) => `End — © ${year} Eververdants`,
  },
  zh: {
    searchPlaceholder: "搜索文章",
    searchLabel: "搜索文章",
    clearSearch: "清除搜索",
    all: "全部",
    result: (n: number) => `${n} 条结果`,
    noMatch: "没有匹配的文章。",
    noSection: "这里还没有归档文章。",
    columns: "栏目",
    tags: "标签",
    topics: "专题",
    latest: "最新",
    topicLabel: "所属专题",
    backToHub: "返回导航页",
    backToIndex: "全部文章",
    backToTop: "回到顶部",
    onThisPage: (n?: number) =>
      n === undefined ? "本页目录" : `本页目录 · ${n}`,
    previous: "上一篇",
    next: "下一篇",
    related: "延伸阅读",
    taggedUnder: "标签",
    references: "参考出处",
    copyCode: "复制代码",
    copied: "已复制",
    copyFailed: "复制失败",
    share: "分享",
    copyLink: "复制链接",
    shared: "已复制",
    linkCopied: "已复制",
    openImage: "打开图片查看器",
    lightbox: "图片查看器",
    loading: "载入中",
    loadFailed: "这篇文章没能加载。",
    retry: "重试",
    empty: "还没有发布文章。",
    noTag: "该标签下暂无文章。",
    posts: "篇文章",
    end: (year: number) => `完 — © ${year} Eververdants`,
  },
} as const;
